name: CICD

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run tests with coverage
        run: npm test -- --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Create .env file
        run: |
          echo 'MONGODB_URI: ${{ secrets.MONGODB_URI }}' >> .env
          echo 'JWT_SECRET: ${{ secrets.JWT_SECRET }}' >> .env
          echo 'CLAVE_SECRETA_DE_STRIPE_TEST: ${{ secrets.CLAVE_SECRETA_DE_STRIPE_TEST }}' >> .env
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/turismo-server:latest .
      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/turismo-server:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Pull image from docker hub
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/turismo-server:latest
          docker pull caddy:2
      - name: Stop previous docker-compose deployment
        run: docker-compose down || true
      - name: Prepare docker-compose.yml
        run: |
          sed 's/%%DOCKER_USERNAME%%/${{ secrets.DOCKER_USERNAME }}/g' docker-compose.template.yml > docker-compose.yml
