name: Despliegue a AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  

jobs:
  despliegue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del Código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Instalar Dependencias
        run: npm install  

      - name: Instalar AWS CLI
        run: |
          pip install awsebcli
          export PATH=$PATH:$HOME/.local/bin

      - name: Configurar AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region eu-west-3c 

      - name: Configurar EB CLI
        run: |
          eb init turismo --region eu-west-3c
          
      - name: Despliegue a Elastic Beanstalk
        run: |
          eb deploy Turismo-env
          eb health Turismo-env --wait-environment-to-terminate
