name: Despliegue a AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  despliegue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del Código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Instalar Dependencias
        run: npm install

      - name: Configurar Elastic Beanstalk
        run: |
          eb init -p nodejs-18.x

      - name: Despliegue a Elastic Beanstalk
        run: |
          eb deploy Turismo-env
          eb health Turismo-env --wait-environment-to-terminate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

